RUN easy_install supervisor
ADD ./scripts/foreground.sh /etc/apache2/foreground.sh
ADD ./configs/supervisord.conf /etc/supervisord.conf
RUN chmod 755 /etc/apache2/foreground.sh
RUN mkdir /var/log/supervisor/ && mkdir /var/run/sshd
#
# json CORS support
# apache .htaccess are ignored when AllowOverride None
# RUN echo 'Header set Access-Control-Allow-Origin "*"' > /var/www/.htaccess
# ADD ./configs/htaccess-cors /var/www/.htaccess
#
ADD ./configs/000-default.conf /etc/apache2/sites-available/000-default.conf 
RUN a2enmod headers
ADD ./scripts/start.sh /start.sh
RUN chmod 755 /start.sh
RUN chmod u+s /usr/bin/sudo